/**
 * Maps standard Apple device dimensions to splash screen image files
 * generated by pwa-asset-generator (apple-splash-{width}-{height}.png).
 */

type StartupImageEntry = {
  url: string;
  media: string;
};

const APPLE_SPLASH_SPECS: Array<{
  width: number;
  height: number;
  deviceWidth: number;
  deviceHeight: number;
  pixelRatio: number;
}> = [
  // iPad Pro 12.9"
  { width: 2048, height: 2732, deviceWidth: 1024, deviceHeight: 1366, pixelRatio: 2 },
  // iPad Pro 11"
  { width: 1668, height: 2388, deviceWidth: 834, deviceHeight: 1194, pixelRatio: 2 },
  // iPad 10.2"
  { width: 1620, height: 2160, deviceWidth: 810, deviceHeight: 1080, pixelRatio: 2 },
  // iPad Air 10.9"
  { width: 1640, height: 2360, deviceWidth: 820, deviceHeight: 1180, pixelRatio: 2 },
  // iPad Pro 10.5" / iPad Air 3
  { width: 1668, height: 2224, deviceWidth: 834, deviceHeight: 1112, pixelRatio: 2 },
  // iPad 9.7" / iPad mini
  { width: 1536, height: 2048, deviceWidth: 768, deviceHeight: 1024, pixelRatio: 2 },
  // iPad mini 6
  { width: 1488, height: 2266, deviceWidth: 744, deviceHeight: 1133, pixelRatio: 2 },
  // iPhone 16 Pro Max
  { width: 1320, height: 2868, deviceWidth: 440, deviceHeight: 956, pixelRatio: 3 },
  // iPhone 16 Pro
  { width: 1206, height: 2622, deviceWidth: 402, deviceHeight: 874, pixelRatio: 3 },
  // iPhone 15 Plus / 15 Pro Max / 14 Plus
  { width: 1290, height: 2796, deviceWidth: 430, deviceHeight: 932, pixelRatio: 3 },
  // iPhone 16 / 16 Plus
  { width: 1260, height: 2736, deviceWidth: 420, deviceHeight: 912, pixelRatio: 3 },
  // iPhone 15 / 15 Pro / 14 Pro
  { width: 1179, height: 2556, deviceWidth: 393, deviceHeight: 852, pixelRatio: 3 },
  // iPhone 14 / 13 / 13 Pro / 12 / 12 Pro
  { width: 1170, height: 2532, deviceWidth: 390, deviceHeight: 844, pixelRatio: 3 },
  // iPhone 14 Pro Max / 13 Pro Max
  { width: 1284, height: 2778, deviceWidth: 428, deviceHeight: 926, pixelRatio: 3 },
  // iPhone X / XS / 11 Pro
  { width: 1125, height: 2436, deviceWidth: 375, deviceHeight: 812, pixelRatio: 3 },
  // iPhone XR / 11 / XS Max / 11 Pro Max @3x
  { width: 1242, height: 2688, deviceWidth: 414, deviceHeight: 896, pixelRatio: 3 },
  // iPhone XR / 11 @2x
  { width: 828, height: 1792, deviceWidth: 414, deviceHeight: 896, pixelRatio: 2 },
  // iPhone 8 Plus / 7 Plus / 6s Plus
  { width: 1242, height: 2208, deviceWidth: 414, deviceHeight: 736, pixelRatio: 3 },
  // iPhone SE 2 / 8 / 7 / 6s / 6
  { width: 750, height: 1334, deviceWidth: 375, deviceHeight: 667, pixelRatio: 2 },
  // iPhone SE 1 / iPod Touch
  { width: 640, height: 1136, deviceWidth: 320, deviceHeight: 568, pixelRatio: 2 },
];

export type SplashBranding = {
  /** Background color (hex, e.g. "#18181B"). */
  bg: string;
  /** Accent color for the glow + icon tile (hex). */
  accent: string;
  /** Studio name — first letter is rendered on the icon tile. */
  studioName: string;
};

/**
 * Encodes the branding into query params so the /api/pwa/apple-splash
 * route is pure rendering — it never has to look up the tenant.
 */
function buildUrl(w: number, h: number, b: SplashBranding): string {
  const bg = encodeURIComponent(b.bg);
  const accent = encodeURIComponent(b.accent);
  const initial = encodeURIComponent(
    (b.studioName?.charAt(0) || "·").toUpperCase(),
  );
  return `/api/pwa/apple-splash?w=${w}&h=${h}&bg=${bg}&a=${accent}&i=${initial}`;
}

export function buildAppleSplashStartupImages(
  branding: SplashBranding,
): StartupImageEntry[] {
  const specific = APPLE_SPLASH_SPECS.map((spec) => ({
    // Dynamic branded splash rendered per-device on the fly. iOS caches
    // the result aggressively so it's only generated once per tenant +
    // device. This guarantees a branded first frame — no flat
    // black/white splash from a missing file.
    url: buildUrl(spec.width, spec.height, branding),
    media: `(device-width: ${spec.deviceWidth}px) and (device-height: ${spec.deviceHeight}px) and (-webkit-device-pixel-ratio: ${spec.pixelRatio}) and (orientation: portrait)`,
  }));

  // Catch-all entries for devices that don't match any exact spec above
  // (e.g. iPhones released after this list was last updated). iOS picks
  // the most specific matching link, falling back to these when no exact
  // device media query matches. Without this fallback, new devices would
  // see a flat white splash because no image is selected.
  const fallback: StartupImageEntry[] = [
    {
      url: buildUrl(1320, 2868, branding),
      media: "(orientation: portrait) and (-webkit-device-pixel-ratio: 3)",
    },
    {
      url: buildUrl(828, 1792, branding),
      media: "(orientation: portrait) and (-webkit-device-pixel-ratio: 2)",
    },
    {
      url: buildUrl(1320, 2868, branding),
      media: "(orientation: portrait)",
    },
  ];

  return [...specific, ...fallback];
}
